// import { Service } from './types';

// export const services: Service[] = [
//   {
//     id: 'instagram',
//     name: 'Instagram',
//     slug: 'instagram',
//     icon: '📷',
//     description: 'Followers, likes, and more.',
//     isPrimary: true,
//     bgGradient: 'from-pink-500 to-purple-600',
//     accentColor: 'bg-pink-500 hover:bg-pink-600',
//     accentText: 'text-pink-600',
//     accentBgLight: 'bg-pink-50',
//     packages: [
//       {
//         id: 'ig-50f',
//         quantity: 50,
//         quantityLabel: '50 Followers',
//         price: 8,
//         description: 'Mixed High Quality Followers',
//         deliveryTime: '1-3 days',
//         quality: 'Mixed Quality',
//         serviceCategory: 'followers',
//         ssmServiceId: 1,
//       },
//       {
//         id: 'ig-100f',
//         quantity: 100,
//         quantityLabel: '100 Followers',
//         price: 13,
//         description: 'Mixed High Quality Followers',
//         deliveryTime: '1-3 days',
//         quality: 'Mixed Quality',
//         serviceCategory: 'followers',
//         ssmServiceId: 1,
//       },
//       {
//         id: 'ig-500f',
//         quantity: 500,
//         quantityLabel: '500 Followers',
//         price: 45,
//         description: 'Indian Real Non-drop Followers',
//         deliveryTime: '2-5 days',
//         quality: 'Real Quality',
//         serviceCategory: 'followers',
//         ssmServiceId: 2,
//       },
//       {
//         id: 'ig-1000f',
//         quantity: 1000,
//         quantityLabel: '1000 Followers',
//         price: 49,
//         description: 'Indian Real Non-drop Followers',
//         deliveryTime: '3-7 days',
//         quality: 'Real Quality',
//         serviceCategory: 'followers',
//         ssmServiceId: 2,
//       },
//       {
//         id: 'ig-2000f',
//         quantity: 2000,
//         quantityLabel: '2000 Followers',
//         price: 79,
//         description: 'Indian Real Non-drop Followers',
//         deliveryTime: '5-10 days',
//         quality: 'Real Quality',
//         serviceCategory: 'followers',
//         ssmServiceId: 2,
//       },
//       {
//         id: 'ig-100l',
//         quantity: 100,
//         quantityLabel: '100 Likes',
//         price: 5,
//         description: 'High Quality Likes',
//         deliveryTime: '1-2 days',
//         quality: 'Mixed Quality',
//         serviceCategory: 'likes',
//         ssmServiceId: 3,
//       },
//       {
//         id: 'ig-500l',
//         quantity: 500,
//         quantityLabel: '500 Likes',
//         price: 15,
//         description: 'High Quality Likes',
//         deliveryTime: '2-4 days',
//         quality: 'Mixed Quality',
//         serviceCategory: 'likes',
//         ssmServiceId: 3,
//       },
//       {
//         id: 'ig-1000l',
//         quantity: 1000,
//         quantityLabel: '1000 Likes',
//         price: 25,
//         description: 'High Quality Likes',
//         deliveryTime: '3-5 days',
//         quality: 'Mixed Quality',
//         serviceCategory: 'likes',
//         ssmServiceId: 3,
//       },
//       {
//         id: 'ig-100c',
//         quantity: 100,
//         quantityLabel: '100 Comments',
//         price: 20,
//         description: 'Real Comments',
//         deliveryTime: '2-5 days',
//         quality: 'Real Quality',
//         serviceCategory: 'comments',
//         ssmServiceId: 4,
//       },
//       {
//         id: 'ig-500c',
//         quantity: 500,
//         quantityLabel: '500 Comments',
//         price: 70,
//         description: 'Real Comments',
//         deliveryTime: '5-10 days',
//         quality: 'Real Quality',
//         serviceCategory: 'comments',
//         ssmServiceId: 4,
//       },
//       {
//         id: 'ig-1000v',
//         quantity: 1000,
//         quantityLabel: '1000 Views',
//         price: 10,
//         description: 'High Quality Views',
//         deliveryTime: '1-2 days',
//         quality: 'Mixed Quality',
//         serviceCategory: 'views',
//         ssmServiceId: 5,
//       },
//       {
//         id: 'ig-5000v',
//         quantity: 5000,
//         quantityLabel: '5000 Views',
//         price: 35,
//         description: 'High Quality Views',
//         deliveryTime: '2-4 days',
//         quality: 'Mixed Quality',
//         serviceCategory: 'views',
//         ssmServiceId: 5,
//       },
//     ],
//   },
//   {
//     id: 'youtube',
//     name: 'YouTube',
//     slug: 'youtube',
//     icon: '▶️',
//     description: 'Best video content daily.',
//     isPrimary: false,
//     bgGradient: 'from-red-500 to-red-700',
//     accentColor: 'bg-red-500 hover:bg-red-600',
//     accentText: 'text-red-600',
//     accentBgLight: 'bg-red-50',
//     packages: [
//       {
//         id: 'yt-100s',
//         quantity: 100,
//         quantityLabel: '100 Subscribers',
//         price: 15,
//         description: 'High Quality Subscribers',
//         deliveryTime: '2-5 days',
//         quality: 'Mixed Quality',
//       },
//       {
//         id: 'yt-500s',
//         quantity: 500,
//         quantityLabel: '500 Subscribers',
//         price: 50,
//         description: 'High Quality Subscribers',
//         deliveryTime: '5-10 days',
//         quality: 'Mixed Quality',
//       },
//       {
//         id: 'yt-1000s',
//         quantity: 1000,
//         quantityLabel: '1000 Subscribers',
//         price: 79,
//         description: 'High Quality Subscribers',
//         deliveryTime: '7-14 days',
//         quality: 'Mixed Quality',
//       },
//       {
//         id: 'yt-1000v',
//         quantity: 1000,
//         quantityLabel: '1000 Views',
//         price: 12,
//         description: 'High Quality Views',
//         deliveryTime: '1-3 days',
//         quality: 'Mixed Quality',
//       },
//       {
//         id: 'yt-5000v',
//         quantity: 5000,
//         quantityLabel: '5000 Views',
//         price: 40,
//         description: 'High Quality Views',
//         deliveryTime: '3-5 days',
//         quality: 'Mixed Quality',
//       },
//     ],
//   },
//   {
//     id: 'facebook',
//     name: 'Facebook',
//     slug: 'facebook',
//     icon: '👥',
//     description: 'Connect with friends and family.',
//     isPrimary: false,
//     bgGradient: 'from-blue-500 to-blue-700',
//     accentColor: 'bg-blue-500 hover:bg-blue-600',
//     accentText: 'text-blue-600',
//     accentBgLight: 'bg-blue-50',
//     packages: [
//       {
//         id: 'fb-100f',
//         quantity: 100,
//         quantityLabel: '100 Followers',
//         price: 10,
//         description: 'Mixed Quality Followers',
//         deliveryTime: '2-4 days',
//         quality: 'Mixed Quality',
//       },
//       {
//         id: 'fb-500f',
//         quantity: 500,
//         quantityLabel: '500 Followers',
//         price: 35,
//         description: 'Mixed Quality Followers',
//         deliveryTime: '4-7 days',
//         quality: 'Mixed Quality',
//       },
//       {
//         id: 'fb-1000f',
//         quantity: 1000,
//         quantityLabel: '1000 Followers',
//         price: 60,
//         description: 'Mixed Quality Followers',
//         deliveryTime: '7-14 days',
//         quality: 'Mixed Quality',
//       },
//     ],
//   },
//   {
//     id: 'tiktok',
//     name: 'TikTok',
//     slug: 'tiktok',
//     icon: '🎵',
//     description: 'Short-form video content.',
//     isPrimary: false,
//     bgGradient: 'from-gray-900 to-black',
//     accentColor: 'bg-gray-800 hover:bg-gray-900',
//     accentText: 'text-gray-800',
//     accentBgLight: 'bg-gray-100',
//     packages: [
//       {
//         id: 'tt-100f',
//         quantity: 100,
//         quantityLabel: '100 Followers',
//         price: 8,
//         description: 'High Quality Followers',
//         deliveryTime: '1-3 days',
//         quality: 'Mixed Quality',
//       },
//       {
//         id: 'tt-500f',
//         quantity: 500,
//         quantityLabel: '500 Followers',
//         price: 25,
//         description: 'High Quality Followers',
//         deliveryTime: '3-5 days',
//         quality: 'Mixed Quality',
//       },
//       {
//         id: 'tt-1000l',
//         quantity: 1000,
//         quantityLabel: '1000 Likes',
//         price: 15,
//         description: 'High Quality Likes',
//         deliveryTime: '1-2 days',
//         quality: 'Mixed Quality',
//       },
//     ],
//   },
//   {
//     id: 'twitter',
//     name: 'Twitter',
//     slug: 'twitter',
//     icon: '𝕏',
//     description: 'Share your thoughts instantly.',
//     isPrimary: false,
//     bgGradient: 'from-sky-400 to-sky-600',
//     accentColor: 'bg-sky-500 hover:bg-sky-600',
//     accentText: 'text-sky-600',
//     accentBgLight: 'bg-sky-50',
//     packages: [
//       {
//         id: 'tw-100f',
//         quantity: 100,
//         quantityLabel: '100 Followers',
//         price: 12,
//         description: 'Mixed Quality Followers',
//         deliveryTime: '2-4 days',
//         quality: 'Mixed Quality',
//       },
//       {
//         id: 'tw-500f',
//         quantity: 500,
//         quantityLabel: '500 Followers',
//         price: 40,
//         description: 'Mixed Quality Followers',
//         deliveryTime: '4-7 days',
//         quality: 'Mixed Quality',
//       },
//     ],
//   },
//   {
//     id: 'spotify',
//     name: 'Spotify',
//     slug: 'spotify',
//     icon: '🎵',
//     description: 'Boost your music streams.',
//     isPrimary: false,
//     bgGradient: 'from-green-500 to-green-700',
//     accentColor: 'bg-green-500 hover:bg-green-600',
//     accentText: 'text-green-600',
//     accentBgLight: 'bg-green-50',
//     packages: [
//       {
//         id: 'sp-100s',
//         quantity: 100,
//         quantityLabel: '100 Streams',
//         price: 8,
//         description: 'High Quality Streams',
//         deliveryTime: '1-2 days',
//         quality: 'Mixed Quality',
//       },
//       {
//         id: 'sp-500s',
//         quantity: 500,
//         quantityLabel: '500 Streams',
//         price: 25,
//         description: 'High Quality Streams',
//         deliveryTime: '2-4 days',
//         quality: 'Mixed Quality',
//       },
//     ],
//   },
// ];

// export function getServiceBySlug(slug: string): Service | undefined {
//   return services.find((s) => s.slug === slug);
// }

// export function getAllServices(): Service[] {
//   return services;
// }

// export function getPrimaryService(): Service | undefined {
//   return services.find((s) => s.isPrimary);
// }

import { Service } from './types';

export const services: Service[] = [
  {
    id: 'instagram',
    name: 'Instagram',
    slug: 'instagram',
    icon: '📷',
    description: 'Followers, likes, comments & reels.',
    isPrimary: true,
    bgGradient: 'from-pink-500 via-rose-500 to-purple-600',
    accentColor: 'bg-gradient-to-r from-pink-500 to-purple-600 hover:from-pink-600 hover:to-purple-700',
    accentText: 'text-pink-600',
    accentBgLight: 'bg-pink-50',
    packages: [
      // Followers
      {
        id: 'ig-50f',
        quantity: 50,
        quantityLabel: '50 Followers',
        price: 8,
        description: 'Mixed High Quality Followers',
        deliveryTime: '1-3 days',
        quality: 'Mixed Quality',
        serviceCategory: 'followers',
        ssmServiceId: 3822,
      },
      {
        id: 'ig-100f',
        quantity: 100,
        quantityLabel: '100 Followers',
        price: 13,
        description: 'Mixed High Quality Followers',
        deliveryTime: '1-3 days',
        quality: 'Mixed Quality',
        serviceCategory: 'followers',
        ssmServiceId: 1,
      },
      {
        id: 'ig-1000f',
        quantity: 1000,
        quantityLabel: '1000 Followers',
        price: 49,
        description: 'Indian Real Non-drop Followers',
        deliveryTime: '3-7 days',
        quality: 'Real Quality',
        serviceCategory: 'followers',
        ssmServiceId: 3822,
      },
      {
        id: 'ig-2000f',
        quantity: 2000,
        quantityLabel: '2000 Followers',
        price: 79,
        description: 'Indian Real Non-drop Followers',
        deliveryTime: '5-10 days',
        quality: 'Real Quality',
        serviceCategory: 'followers',
        ssmServiceId: 3822,
      },
      {
        id: 'ig-5000f',
        quantity: 5000,
        quantityLabel: '5000 Followers',
        price: 99,
        description: 'Indian Real Non-drop Followers',
        deliveryTime: '7-14 days',
        quality: 'Real Quality',
        serviceCategory: 'followers',
        ssmServiceId: 3822,
      },
      {
        id: 'ig-10000f',
        quantity: 10000,
        quantityLabel: '10000 Followers',
        price: 150,
        description: 'Indian Real Non-drop Followers',
        deliveryTime: '10-20 days',
        quality: 'Real Quality',
        serviceCategory: 'followers',
        ssmServiceId: 3822,
      },
      {
        id: 'ig-15000f',
        quantity: 15000,
        quantityLabel: '15000 Followers',
        price: 199,
        description: 'Indian Real Non-drop Followers',
        deliveryTime: '14-25 days',
        quality: 'Real Quality',
        serviceCategory: 'followers',
        ssmServiceId: 3822,
      },
      {
        id: 'ig-25000f',
        quantity: 25000,
        quantityLabel: '25000 Followers',
        price: 299,
        description: 'Indian Real Non-drop Followers',
        deliveryTime: '15-30 days',
        quality: 'Real Quality',
        serviceCategory: 'followers',
        ssmServiceId: 3822,
      },
      {
        id: 'ig-50000f',
        quantity: 50000,
        quantityLabel: '50000 Followers',
        price: 449,
        description: 'Indian Real Non-drop Followers',
        deliveryTime: '20-40 days',
        quality: 'Real Quality',
        serviceCategory: 'followers',
        ssmServiceId: 3822,
      },
      {
        id: 'ig-100kf',
        quantity: 100000,
        quantityLabel: '100K Followers',
        price: 649,
        description: 'Indian Real Non-drop Followers',
        deliveryTime: '30-60 days',
        quality: 'Real Quality',
        serviceCategory: 'followers',
        ssmServiceId: 2,
        isBestSeller: true,
      },
      {
        id: 'ig-1mf',
        quantity: 1000000,
        quantityLabel: '1M Followers',
        price: 499,
        description: 'Indian Real Non-drop Followers',
        deliveryTime: '60-90 days',
        quality: 'Real Quality',
        serviceCategory: 'followers',
        ssmServiceId: 2,
        badge: '🎉 Holi Special',
      },
      // Likes
      {
        id: 'ig-1000l',
        quantity: 1000,
        quantityLabel: '1000 Likes',
        price: 30,
        description: 'Indian Real Non-drop Likes',
        deliveryTime: '1-2 days',
        quality: 'Real Quality',
        serviceCategory: 'likes',
        ssmServiceId: 3924,
      },
      {
        id: 'ig-2000l',
        quantity: 2000,
        quantityLabel: '2000 Likes',
        price: 48,
        description: 'Indian Real Non-drop Likes',
        deliveryTime: '2-3 days',
        quality: 'Real Quality',
        serviceCategory: 'likes',
        ssmServiceId: 3924,
      },
      {
        id: 'ig-5000l',
        quantity: 5000,
        quantityLabel: '5000 Likes',
        price: 69,
        description: 'Indian Real Non-drop Likes',
        deliveryTime: '3-5 days',
        quality: 'Real Quality',
        serviceCategory: 'likes',
        ssmServiceId: 3924,
      },
      {
        id: 'ig-10000l',
        quantity: 10000,
        quantityLabel: '10000 Likes',
        price: 99,
        description: 'Indian Real Non-drop Likes',
        deliveryTime: '4-7 days',
        quality: 'Real Quality',
        serviceCategory: 'likes',
        ssmServiceId: 3924,
      },
      {
        id: 'ig-20000l',
        quantity: 20000,
        quantityLabel: '20000 Likes',
        price: 149,
        description: 'Indian Real Non-drop Likes',
        deliveryTime: '5-10 days',
        quality: 'Real Quality',
        serviceCategory: 'likes',
        ssmServiceId: 3,
      },
      // Comments
      {
        id: 'ig-100c',
        quantity: 100,
        quantityLabel: '100 Comments',
        price: 35,
        description: 'Indian Girls & Boys Mixed.',
        deliveryTime: '2-5 days',
        quality: 'Real Quality',
        serviceCategory: 'comments',
        ssmServiceId: 670,
      },
      {
        id: 'ig-200c',
        quantity: 200,
        quantityLabel: '200 Comments',
        price: 65,
        description: 'Indian Girls & Boys Mixed.',
        deliveryTime: '3-6 days',
        quality: 'Real Quality',
        serviceCategory: 'comments',
        ssmServiceId: 670,
      },
      {
        id: 'ig-500c',
        quantity: 500,
        quantityLabel: '500 Comments',
        price: 150,
        description: 'Indian Girls & Boys Mixed.',
        deliveryTime: '5-10 days',
        quality: 'Real Quality',
        serviceCategory: 'comments',
        ssmServiceId: 670,
      },
      {
        id: 'ig-1000c',
        quantity: 1000,
        quantityLabel: '1000 Comments',
        price: 280,
        description: 'Indian Girls & Boys Mixed.',
        deliveryTime: '7-14 days',
        quality: 'Real Quality',
        serviceCategory: 'comments',
        ssmServiceId: 4,
      },
      // Reel Views
      {
        id: 'ig-5000rv',
        quantity: 5000,
        quantityLabel: '5000 Reel Views',
        price: 7,
        description: 'Boost views on your Instagram reels.',
        deliveryTime: '1-2 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
        ssmServiceId: 602,
      },
      {
        id: 'ig-10000rv',
        quantity: 10000,
        quantityLabel: '10000 Reel Views',
        price: 12,
        description: 'Boost views on your Instagram reels.',
        deliveryTime: '1-2 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
        ssmServiceId: 602,
      },
      {
        id: 'ig-25000rv',
        quantity: 25000,
        quantityLabel: '25000 Reel Views',
        price: 25,
        description: 'Boost views on your Instagram reels.',
        deliveryTime: '2-3 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
        ssmServiceId: 602,
      },
      {
        id: 'ig-50000rv',
        quantity: 50000,
        quantityLabel: '50000 Reel Views',
        price: 45,
        description: 'Boost views on your Instagram reels.',
        deliveryTime: '2-4 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
        ssmServiceId: 602,
      },
      {
        id: 'ig-100000rv',
        quantity: 100000,
        quantityLabel: '100000 Reel Views',
        price: 75,
        description: 'Boost views on your Instagram reels.',
        deliveryTime: '3-5 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
        ssmServiceId: 602,
      },
      {
        id: 'ig-200000rv',
        quantity: 200000,
        quantityLabel: '200000 Reel Views',
        price: 90,
        description: 'Boost views on your Instagram reels.',
        deliveryTime: '4-6 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
        ssmServiceId: 602,
      },
      {
        id: 'ig-300000rv',
        quantity: 300000,
        quantityLabel: '300000 Reel Views',
        price: 109,
        description: 'Boost views on your Instagram reels.',
        deliveryTime: '5-7 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
        ssmServiceId: 602,
      },
      {
        id: 'ig-500000rv',
        quantity: 500000,
        quantityLabel: '500000 Reel Views',
        price: 125,
        description: 'Boost views on your Instagram reels.',
        deliveryTime: '6-10 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
        ssmServiceId: 602,
      },
      {
        id: 'ig-1mrv',
        quantity: 1000000,
        quantityLabel: '1000000 Reel Views',
        price: 219,
        description: 'Boost views on your Instagram reels.',
        deliveryTime: '10-15 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
        ssmServiceId: 5,
      },
      // Story Views
      {
        id: 'ig-1000sv',
        quantity: 1000,
        quantityLabel: '1000 Story Views',
        price: 24,
        description: 'Boost views on your Instagram stories.',
        deliveryTime: '1-2 days',
        quality: 'Mixed Quality',
        serviceCategory: 'story_views',
        ssmServiceId: 6,
      },
      {
        id: 'ig-2000sv',
        quantity: 2000,
        quantityLabel: '2000 Story Views',
        price: 35,
        description: 'Boost views on your Instagram stories.',
        deliveryTime: '1-2 days',
        quality: 'Mixed Quality',
        serviceCategory: 'story_views',
        ssmServiceId: 6,
      },
      {
        id: 'ig-5000sv',
        quantity: 5000,
        quantityLabel: '5000 Story Views',
        price: 45,
        description: 'Boost views on your Instagram stories.',
        deliveryTime: '2-3 days',
        quality: 'Mixed Quality',
        serviceCategory: 'story_views',
        ssmServiceId: 6,
      },
      {
        id: 'ig-10000sv',
        quantity: 10000,
        quantityLabel: '10000 Story Views',
        price: 85,
        description: 'Boost views on your Instagram stories.',
        deliveryTime: '2-4 days',
        quality: 'Mixed Quality',
        serviceCategory: 'story_views',
        ssmServiceId: 6,
      },
    ],
  },
  {
    id: 'youtube',
    name: 'YouTube',
    slug: 'youtube',
    icon: '▶️',
    description: 'Subscribers, views & watch time.',
    isPrimary: false,
    bgGradient: 'from-red-500 to-red-700',
    accentColor: 'bg-red-500 hover:bg-red-600',
    accentText: 'text-red-600',
    accentBgLight: 'bg-red-50',
    packages: [
      {
        id: 'yt-100s',
        quantity: 100,
        quantityLabel: '100 Subscribers',
        price: 15,
        description: 'High Quality Subscribers',
        deliveryTime: '2-5 days',
        quality: 'Mixed Quality',
        serviceCategory: 'subscribers',
      },
      {
        id: 'yt-500s',
        quantity: 500,
        quantityLabel: '500 Subscribers',
        price: 50,
        description: 'High Quality Subscribers',
        deliveryTime: '5-10 days',
        quality: 'Mixed Quality',
        serviceCategory: 'subscribers',
      },
      {
        id: 'yt-1000s',
        quantity: 1000,
        quantityLabel: '1000 Subscribers',
        price: 79,
        description: 'High Quality Subscribers',
        deliveryTime: '7-14 days',
        quality: 'Mixed Quality',
        serviceCategory: 'subscribers',
      },
      {
        id: 'yt-1000v',
        quantity: 1000,
        quantityLabel: '1000 Views',
        price: 12,
        description: 'High Quality Views',
        deliveryTime: '1-3 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
      },
      {
        id: 'yt-5000v',
        quantity: 5000,
        quantityLabel: '5000 Views',
        price: 40,
        description: 'High Quality Views',
        deliveryTime: '3-5 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
      },
    ],
  },
  {
    id: 'facebook',
    name: 'Facebook',
    slug: 'facebook',
    icon: '👥',
    description: 'Page likes, followers & more.',
    isPrimary: false,
    bgGradient: 'from-blue-500 to-blue-700',
    accentColor: 'bg-blue-500 hover:bg-blue-600',
    accentText: 'text-blue-600',
    accentBgLight: 'bg-blue-50',
    packages: [
      {
        id: 'fb-100f',
        quantity: 100,
        quantityLabel: '100 Followers',
        price: 10,
        description: 'Mixed Quality Followers',
        deliveryTime: '2-4 days',
        quality: 'Mixed Quality',
        serviceCategory: 'followers',
      },
      {
        id: 'fb-500f',
        quantity: 500,
        quantityLabel: '500 Followers',
        price: 35,
        description: 'Mixed Quality Followers',
        deliveryTime: '4-7 days',
        quality: 'Mixed Quality',
        serviceCategory: 'followers',
      },
      {
        id: 'fb-1000f',
        quantity: 1000,
        quantityLabel: '1000 Followers',
        price: 60,
        description: 'Mixed Quality Followers',
        deliveryTime: '7-14 days',
        quality: 'Mixed Quality',
        serviceCategory: 'followers',
      },
    ],
  },
  {
    id: 'netflix',
    name: 'Netflix',
    slug: 'netflix',
    icon: '🎬',
    description: 'Watch your favorite shows.',
    isPrimary: false,
    bgGradient: 'from-red-600 to-red-900',
    accentColor: 'bg-red-600 hover:bg-red-700',
    accentText: 'text-red-700',
    accentBgLight: 'bg-red-50',
    packages: [
      {
        id: 'nf-1m',
        quantity: 1,
        quantityLabel: '1 Month Plan',
        price: 149,
        description: 'Netflix Premium Access',
        deliveryTime: '1-2 hours',
        quality: 'Premium',
        serviceCategory: 'subscription',
      },
      {
        id: 'nf-3m',
        quantity: 3,
        quantityLabel: '3 Month Plan',
        price: 399,
        description: 'Netflix Premium Access',
        deliveryTime: '1-2 hours',
        quality: 'Premium',
        serviceCategory: 'subscription',
      },
    ],
  },
  {
    id: 'amazon-prime',
    name: 'Amazon Prime',
    slug: 'amazon-prime',
    icon: '📦',
    description: 'Shop and stream.',
    isPrimary: false,
    bgGradient: 'from-sky-500 to-blue-700',
    accentColor: 'bg-sky-500 hover:bg-sky-600',
    accentText: 'text-sky-600',
    accentBgLight: 'bg-sky-50',
    packages: [
      {
        id: 'ap-1m',
        quantity: 1,
        quantityLabel: '1 Month Plan',
        price: 99,
        description: 'Amazon Prime Access',
        deliveryTime: '1-2 hours',
        quality: 'Premium',
        serviceCategory: 'subscription',
      },
      {
        id: 'ap-3m',
        quantity: 3,
        quantityLabel: '3 Month Plan',
        price: 249,
        description: 'Amazon Prime Access',
        deliveryTime: '1-2 hours',
        quality: 'Premium',
        serviceCategory: 'subscription',
      },
    ],
  },
  {
    id: 'spotify',
    name: 'Spotify',
    slug: 'spotify',
    icon: '🎵',
    description: 'Listen to music and podcasts.',
    isPrimary: false,
    bgGradient: 'from-green-500 to-green-700',
    accentColor: 'bg-green-500 hover:bg-green-600',
    accentText: 'text-green-600',
    accentBgLight: 'bg-green-50',
    packages: [
      {
        id: 'sp-100s',
        quantity: 100,
        quantityLabel: '100 Streams',
        price: 8,
        description: 'High Quality Streams',
        deliveryTime: '1-2 days',
        quality: 'Mixed Quality',
        serviceCategory: 'streams',
      },
      {
        id: 'sp-500s',
        quantity: 500,
        quantityLabel: '500 Streams',
        price: 25,
        description: 'High Quality Streams',
        deliveryTime: '2-4 days',
        quality: 'Mixed Quality',
        serviceCategory: 'streams',
      },
    ],
  },
  {
    id: 'telegram',
    name: 'Telegram',
    slug: 'telegram',
    icon: '✈️',
    description: 'Grow your Telegram presence.',
    isPrimary: false,
    bgGradient: 'from-sky-400 to-cyan-600',
    accentColor: 'bg-sky-500 hover:bg-sky-600',
    accentText: 'text-sky-600',
    accentBgLight: 'bg-sky-50',
    packages: [
      {
        id: 'tg-100m',
        quantity: 100,
        quantityLabel: '100 Members',
        price: 12,
        description: 'Real Channel Members',
        deliveryTime: '1-3 days',
        quality: 'Mixed Quality',
        serviceCategory: 'members',
      },
      {
        id: 'tg-500m',
        quantity: 500,
        quantityLabel: '500 Members',
        price: 45,
        description: 'Real Channel Members',
        deliveryTime: '3-5 days',
        quality: 'Mixed Quality',
        serviceCategory: 'members',
      },
      {
        id: 'tg-1000m',
        quantity: 1000,
        quantityLabel: '1000 Members',
        price: 79,
        description: 'Real Channel Members',
        deliveryTime: '5-10 days',
        quality: 'Mixed Quality',
        serviceCategory: 'members',
      },
    ],
  },
];

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find((s) => s.slug === slug);
}

export function getAllServices(): Service[] {
  return services;
}

export function getPrimaryService(): Service | undefined {
  return services.find((s) => s.isPrimary);
}

