import { Service } from './types';

export const services: Service[] = [
  {
    id: 'instagram',
    name: 'Instagram',
    slug: 'instagram',
    icon: '📷',
    description: 'Followers, likes, and more.',
    isPrimary: true,
    bgGradient: 'from-pink-500 to-purple-600',
    accentColor: 'bg-pink-500 hover:bg-pink-600',
    accentText: 'text-pink-600',
    accentBgLight: 'bg-pink-50',
    packages: [
      {
        id: 'ig-50f',
        quantity: 50,
        quantityLabel: '50 Followers',
        price: 8,
        description: 'Mixed High Quality Followers',
        deliveryTime: '1-3 days',
        quality: 'Mixed Quality',
        serviceCategory: 'followers',
        ssmServiceId: 1,
      },
      {
        id: 'ig-100f',
        quantity: 100,
        quantityLabel: '100 Followers',
        price: 13,
        description: 'Mixed High Quality Followers',
        deliveryTime: '1-3 days',
        quality: 'Mixed Quality',
        serviceCategory: 'followers',
        ssmServiceId: 1,
      },
      {
        id: 'ig-500f',
        quantity: 500,
        quantityLabel: '500 Followers',
        price: 45,
        description: 'Indian Real Non-drop Followers',
        deliveryTime: '2-5 days',
        quality: 'Real Quality',
        serviceCategory: 'followers',
        ssmServiceId: 2,
      },
      {
        id: 'ig-1000f',
        quantity: 1000,
        quantityLabel: '1000 Followers',
        price: 49,
        description: 'Indian Real Non-drop Followers',
        deliveryTime: '3-7 days',
        quality: 'Real Quality',
        serviceCategory: 'followers',
        ssmServiceId: 2,
      },
      {
        id: 'ig-2000f',
        quantity: 2000,
        quantityLabel: '2000 Followers',
        price: 79,
        description: 'Indian Real Non-drop Followers',
        deliveryTime: '5-10 days',
        quality: 'Real Quality',
        serviceCategory: 'followers',
        ssmServiceId: 2,
      },
      {
        id: 'ig-100l',
        quantity: 100,
        quantityLabel: '100 Likes',
        price: 5,
        description: 'High Quality Likes',
        deliveryTime: '1-2 days',
        quality: 'Mixed Quality',
        serviceCategory: 'likes',
        ssmServiceId: 3,
      },
      {
        id: 'ig-500l',
        quantity: 500,
        quantityLabel: '500 Likes',
        price: 15,
        description: 'High Quality Likes',
        deliveryTime: '2-4 days',
        quality: 'Mixed Quality',
        serviceCategory: 'likes',
        ssmServiceId: 3,
      },
      {
        id: 'ig-1000l',
        quantity: 1000,
        quantityLabel: '1000 Likes',
        price: 25,
        description: 'High Quality Likes',
        deliveryTime: '3-5 days',
        quality: 'Mixed Quality',
        serviceCategory: 'likes',
        ssmServiceId: 3,
      },
      {
        id: 'ig-100c',
        quantity: 100,
        quantityLabel: '100 Comments',
        price: 20,
        description: 'Real Comments',
        deliveryTime: '2-5 days',
        quality: 'Real Quality',
        serviceCategory: 'comments',
        ssmServiceId: 4,
      },
      {
        id: 'ig-500c',
        quantity: 500,
        quantityLabel: '500 Comments',
        price: 70,
        description: 'Real Comments',
        deliveryTime: '5-10 days',
        quality: 'Real Quality',
        serviceCategory: 'comments',
        ssmServiceId: 4,
      },
      {
        id: 'ig-1000v',
        quantity: 1000,
        quantityLabel: '1000 Views',
        price: 10,
        description: 'High Quality Views',
        deliveryTime: '1-2 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
        ssmServiceId: 5,
      },
      {
        id: 'ig-5000v',
        quantity: 5000,
        quantityLabel: '5000 Views',
        price: 35,
        description: 'High Quality Views',
        deliveryTime: '2-4 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
        ssmServiceId: 5,
      },
    ],
  },
  {
    id: 'youtube',
    name: 'YouTube',
    slug: 'youtube',
    icon: '▶️',
    description: 'Best video content daily.',
    isPrimary: false,
    bgGradient: 'from-red-500 to-red-700',
    accentColor: 'bg-red-500 hover:bg-red-600',
    accentText: 'text-red-600',
    accentBgLight: 'bg-red-50',
    packages: [
      {
        id: 'yt-100s',
        quantity: 100,
        quantityLabel: '100 Subscribers',
        price: 15,
        description: 'High Quality Subscribers',
        deliveryTime: '2-5 days',
        quality: 'Mixed Quality',
      },
      {
        id: 'yt-500s',
        quantity: 500,
        quantityLabel: '500 Subscribers',
        price: 50,
        description: 'High Quality Subscribers',
        deliveryTime: '5-10 days',
        quality: 'Mixed Quality',
      },
      {
        id: 'yt-1000s',
        quantity: 1000,
        quantityLabel: '1000 Subscribers',
        price: 79,
        description: 'High Quality Subscribers',
        deliveryTime: '7-14 days',
        quality: 'Mixed Quality',
      },
      {
        id: 'yt-1000v',
        quantity: 1000,
        quantityLabel: '1000 Views',
        price: 12,
        description: 'High Quality Views',
        deliveryTime: '1-3 days',
        quality: 'Mixed Quality',
      },
      {
        id: 'yt-5000v',
        quantity: 5000,
        quantityLabel: '5000 Views',
        price: 40,
        description: 'High Quality Views',
        deliveryTime: '3-5 days',
        quality: 'Mixed Quality',
      },
    ],
  },
  {
    id: 'facebook',
    name: 'Facebook',
    slug: 'facebook',
    icon: '👥',
    description: 'Connect with friends and family.',
    isPrimary: false,
    bgGradient: 'from-blue-500 to-blue-700',
    accentColor: 'bg-blue-500 hover:bg-blue-600',
    accentText: 'text-blue-600',
    accentBgLight: 'bg-blue-50',
    packages: [
      {
        id: 'fb-100f',
        quantity: 100,
        quantityLabel: '100 Followers',
        price: 10,
        description: 'Mixed Quality Followers',
        deliveryTime: '2-4 days',
        quality: 'Mixed Quality',
      },
      {
        id: 'fb-500f',
        quantity: 500,
        quantityLabel: '500 Followers',
        price: 35,
        description: 'Mixed Quality Followers',
        deliveryTime: '4-7 days',
        quality: 'Mixed Quality',
      },
      {
        id: 'fb-1000f',
        quantity: 1000,
        quantityLabel: '1000 Followers',
        price: 60,
        description: 'Mixed Quality Followers',
        deliveryTime: '7-14 days',
        quality: 'Mixed Quality',
      },
    ],
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    slug: 'tiktok',
    icon: '🎵',
    description: 'Short-form video content.',
    isPrimary: false,
    bgGradient: 'from-gray-900 to-black',
    accentColor: 'bg-gray-800 hover:bg-gray-900',
    accentText: 'text-gray-800',
    accentBgLight: 'bg-gray-100',
    packages: [
      {
        id: 'tt-100f',
        quantity: 100,
        quantityLabel: '100 Followers',
        price: 8,
        description: 'High Quality Followers',
        deliveryTime: '1-3 days',
        quality: 'Mixed Quality',
      },
      {
        id: 'tt-500f',
        quantity: 500,
        quantityLabel: '500 Followers',
        price: 25,
        description: 'High Quality Followers',
        deliveryTime: '3-5 days',
        quality: 'Mixed Quality',
      },
      {
        id: 'tt-1000l',
        quantity: 1000,
        quantityLabel: '1000 Likes',
        price: 15,
        description: 'High Quality Likes',
        deliveryTime: '1-2 days',
        quality: 'Mixed Quality',
      },
    ],
  },
  {
    id: 'twitter',
    name: 'Twitter',
    slug: 'twitter',
    icon: '𝕏',
    description: 'Share your thoughts instantly.',
    isPrimary: false,
    bgGradient: 'from-sky-400 to-sky-600',
    accentColor: 'bg-sky-500 hover:bg-sky-600',
    accentText: 'text-sky-600',
    accentBgLight: 'bg-sky-50',
    packages: [
      {
        id: 'tw-100f',
        quantity: 100,
        quantityLabel: '100 Followers',
        price: 12,
        description: 'Mixed Quality Followers',
        deliveryTime: '2-4 days',
        quality: 'Mixed Quality',
      },
      {
        id: 'tw-500f',
        quantity: 500,
        quantityLabel: '500 Followers',
        price: 40,
        description: 'Mixed Quality Followers',
        deliveryTime: '4-7 days',
        quality: 'Mixed Quality',
      },
    ],
  },
  {
    id: 'spotify',
    name: 'Spotify',
    slug: 'spotify',
    icon: '🎵',
    description: 'Boost your music streams.',
    isPrimary: false,
    bgGradient: 'from-green-500 to-green-700',
    accentColor: 'bg-green-500 hover:bg-green-600',
    accentText: 'text-green-600',
    accentBgLight: 'bg-green-50',
    packages: [
      {
        id: 'sp-100s',
        quantity: 100,
        quantityLabel: '100 Streams',
        price: 8,
        description: 'High Quality Streams',
        deliveryTime: '1-2 days',
        quality: 'Mixed Quality',
      },
      {
        id: 'sp-500s',
        quantity: 500,
        quantityLabel: '500 Streams',
        price: 25,
        description: 'High Quality Streams',
        deliveryTime: '2-4 days',
        quality: 'Mixed Quality',
      },
    ],
  },
];

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find((s) => s.slug === slug);
}

export function getAllServices(): Service[] {
  return services;
}

export function getPrimaryService(): Service | undefined {
  return services.find((s) => s.isPrimary);
}
